import { Package } from '@/types';

export const frameworkApps: Package[] = [
  {
    id: 'react',
    name: 'React (via Vite)',
    description: '⚛️ The most popular frontend library',
    category: 'framework',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'npm install -g create-vite',
        linuxCommand: 'npm install -g create-vite',
      },
    ],
    linuxCommandTemplate: 'npm install -g create-vite@${VERSION}',
    macosCommandTemplate: 'npm install -g create-vite@${VERSION}',
  },
  {
    id: 'vue',
    name: 'Vue.js',
    description: '🖖 The progressive JavaScript framework',
    category: 'framework',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'npm install -g @vue/cli',
        linuxCommand: 'npm install -g @vue/cli',
      },
    ],
    linuxCommandTemplate: 'npm install -g @vue/cli@${VERSION}',
    macosCommandTemplate: 'npm install -g @vue/cli@${VERSION}',
  },
  {
    id: 'angular',
    name: 'Angular',
    description: '🅰️ Platform for building mobile & desktop web apps',
    category: 'framework',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'npm install -g @angular/cli',
        linuxCommand: 'npm install -g @angular/cli',
      },
    ],
    linuxCommandTemplate: 'npm install -g @angular/cli@${VERSION}',
    macosCommandTemplate: 'npm install -g @angular/cli@${VERSION}',
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    description: '▲ The React framework for the web',
    category: 'framework',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'npm install -g create-next-app',
        linuxCommand: 'npm install -g create-next-app',
      },
    ],
    linuxCommandTemplate: 'npm install -g create-next-app@${VERSION}',
    macosCommandTemplate: 'npm install -g create-next-app@${VERSION}',
  },
  {
    id: 'django',
    name: 'Django',
    description: '🎸 High-level Python web framework',
    category: 'framework',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'pip3 install Django',
        linuxCommand: 'pip3 install Django',
      },
    ],
    linuxCommandTemplate: 'pip3 install Django==${VERSION_NO_V}',
    macosCommandTemplate: 'pip3 install Django==${VERSION_NO_V}',
  },
  {
    id: 'flask',
    name: 'Flask',
    description: '🧪 Lightweight Python web framework',
    category: 'framework',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'pip3 install Flask',
        linuxCommand: 'pip3 install Flask',
      },
    ],
    linuxCommandTemplate: 'pip3 install Flask==${VERSION_NO_V}',
    macosCommandTemplate: 'pip3 install Flask==${VERSION_NO_V}',
  },
  {
    id: 'express',
    name: 'Express',
    description: '🚂 Fast, unopinionated web framework for Node.js',
    category: 'framework',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'npm install -g express-generator',
        linuxCommand: 'npm install -g express-generator',
      },
    ],
    linuxCommandTemplate: 'npm install -g express-generator@${VERSION}',
    macosCommandTemplate: 'npm install -g express-generator@${VERSION}',
  },
];
